CycloneDX/cyclonedx-dotnet

- CycloneDX/Program.cs
This commit should prevent the tool from throwing a null reference exception if the solution file isn't specified or the output directory doesn't already exist
As a side note, let me know if you'd like me to add code to automatically select a sln file if only one exists in the directory where the tool is run
> Preventing null reference exceptions on missing data

- CycloneDX/Program.cs
Adding support for some basic parsing of the new license expression field, which is found in more recent nuget packages.  [https://github.com/NuGet/Home/wiki/Packaging-License-within-the-nupkg#project-properties](url)
> Add basic support for the new license expression field

- CycloneDX/Model/License.cs
- CycloneDX/Program.cs
Include the license URL when the license id is not available in the package metadata. This allows us to to further post-processing on the BOM to determine what the license for the package is. This is helpful since most nuget packages don't currently include the license id.
I had to bump the schema version to 1.1 to support this change.
> Include license URL if license id is not available. Moved to 1.1 schema

- CycloneDX/Program.cs
If there are no packages in the project file, such as in .NET Framework
projects, this change will make it check for and process a packages.config
file in the same directory as the project file.
Should fix #10.
> Processes packages.config if no packages are found in the project file

- CycloneDX.IntegrationTests/CycloneDX.IntegrationTests.csproj
- CycloneDX.Tests/CycloneDX.Tests.csproj
- CycloneDX/CycloneDX.csproj
This just bundles the existing dependabot pull requests into a single one to confirm the tests all pass.
The tests haven't run on any of those pull requests. I suspect that is because they were created before #37 was merged.
> Bump dependencies

- CycloneDX.Tests/GithubServiceTests.cs
- CycloneDX.Tests/NugetServiceTests.cs
- CycloneDX/ExitCode.cs
- CycloneDX/Models/GithubLicense.cs
- CycloneDX/Program.cs
- CycloneDX/Services/GithubService.cs
- CycloneDX/Services/NugetService.cs
- README.md
This builds on pull request #39, thanks @ST-Apps
I'll run a custom build of this against my 200+ repos for a few days to validate this before switching this PR from draft.
@stevespringett this functionality is really awesome and would be great to get out in the wild. So if there is a particular day/time you can spare to push out a new release let me know. Just so I can make sure I've validated the results and updated this PR before then.
> Tests for pull request #39 Added license handling using Github API when possible

- .github/workflows/dotnetcore.yml
While working on #42 I had some tests that were passing on Ubuntu but not Windows.
This change just does what's on the label.
I also removed the `dotnet build` step as `dotnet test` runs a build anyway and the output isn't being used.
> Run tests for Windows, Linux and MacOS

- .github/workflows/dotnetcore.yml
- CycloneDX.IntegrationTests/CycloneDX.IntegrationTests.csproj
- CycloneDX.Tests/CycloneDX.Tests.csproj
- CycloneDX.sln
- CycloneDX/CycloneDX.csproj
- README.md
I do not have knowledge of your CI/CD pipeline so that it pushes it up to dotnet install tool will actually be downloading the 3.1. version. 3.1 is the de-facto version MS wants everyone to use.
> Bumped versions to support .NET Core 3.1

- CycloneDX.Tests/NugetServiceTests.cs
- CycloneDX/Services/NugetService.cs
Sorry @stevespringett, I introduced a regression that would cause bom generation to fail if there are any references to packages that don't exist in an available feed. Fixes #74
> Fix nuget 404 regression

- CycloneDX.IntegrationTests/CycloneDX.IntegrationTests.csproj
- CycloneDX.Tests/CycloneDX.Tests.csproj
- CycloneDX/CycloneDX.csproj
Includes #80 and #81. Then removes unnecessary package reference that causes issue when only one package reference is bumped in Dependabot PRs.
> Dependency bump

- CycloneDX/ExitCode.cs
- CycloneDX/Program.cs
Makes the tool fail more gracefully for invalid package references that
cause `dotnet restore` to fail.
> Catch DotnetRestoreExceptions

- CycloneDX/Services/ComponentService.cs
- CycloneDX/Services/ProjectFileService.cs
TryDequeue is not available in .net standard 2. This is to support
moving the services into the core library. Which currently targets .net
core 2.1 and 3.1. .net core 2.1 only supports .net standard 2, not 2.1.
> Use Queue<T>.Dequeue instead of Queue<T>.TryDequeue

- .github/workflows/dotnetcore.yml
- CycloneDX.Core.Tests/ComponentServiceTests.cs
- CycloneDX.Core.Tests/GithubServiceTests.cs
- CycloneDX.Core.Tests/NugetServiceTests.cs
- CycloneDX.Core.Tests/PackagesFileServiceTests.cs
- CycloneDX.Core.Tests/ProjectFileServiceTests.cs
- CycloneDX.Core.Tests/SolutionFileServiceTests.cs
- CycloneDX.Core/AssemblyInfo.cs
- CycloneDX.Core/CycloneDX.Core.csproj
- CycloneDX.Core/Extensions/HttpClientExtensions.cs
- CycloneDX.Core/Models/Component.cs
- CycloneDX.Core/Models/ExternalReference.cs
- CycloneDX.Core/Models/Hash.cs
- CycloneDX.Core/Models/NugetPackage.cs
- CycloneDX.Core/Services/ComponentService.cs
- CycloneDX.Core/Services/DotnetCommandService.cs
- CycloneDX.Core/Services/DotnetUtilsService.cs
- CycloneDX.Core/Services/GithubService.cs
- CycloneDX.Core/Services/NugetService.cs
- CycloneDX.Core/Services/PackagesFileService.cs
- CycloneDX.Core/Services/ProjectFileService.cs
- CycloneDX.Core/Services/SolutionFileService.cs
- CycloneDX.Core/Utils.cs
- CycloneDX.IntegrationTests/IntegrationTests.cs
- CycloneDX.Tests/ProgramTests.cs
- CycloneDX/AssemblyInfo.cs
- CycloneDX/CycloneDX.csproj
- CycloneDX/Program.cs
Incorporate FxCop analyzer checks for code quality.
Suppresses some checks that are just "noise" in the current context and fix some identified code quality issues.
In particular, some of them relate to globalization so should be revisited if we start doing localized versions of the tool.
> Run FxCop analyzers for PRs and builds

- CycloneDX.Core.Tests/NugetServiceTests.cs
- CycloneDX.Core/Services/NugetService.cs
- CycloneDX/Program.cs
- README.md
To address issue #96 Make github license lookup optional
In particular to support operating in restricted environments without internet access.
> Optional licence resolution

- .github/workflows/dotnetcore.yml
- .github/workflows/release.yml
Turns out all the github hosted runners have .NET SDKs already installed.
> Remove explicit setup of .NET SDKs

- CycloneDX.Core/Extensions/HttpClientExtensions.cs
Artifactory tends to return 405 errors when a file can't be found,
resulting in failures if using a private NuGet repo hosted on
Artifactory for the URL parameter.
> Add Artifactory compatibility to HttpClientExtensions

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- README.md
This is mainly to make switching between implementations for maintainers easier. But can also be handy for new contributors.
> Add devcontainer configuration

- CycloneDX.Tests/NugetServiceTests.cs
- CycloneDX/Program.cs
- CycloneDX/Services/NugetService.cs
- README.md
Add a flag (`disable-hash-computation`) to disable the computation of hash for components.
Main reason for that is to speed up the BOM generation when we don't need hash for components.
I maintaned the hash only in case it was already available as `.nupkg.sha512`, because my assumption is that in this case the performance penality is small.
> add flag to disable hash computation for packages

- CycloneDX.Tests/GithubServiceTests.cs
- CycloneDX/Services/GithubService.cs
I stumbled upon a number of GitHub license urls, which seems reasonable to add support for when checking for the checking the GitHub api for license details.
These are the GitHub license urls I found that I would like to be able to extract license details about:
- https://raw.githubusercontent.com/moq/moq4/master/License.txt
- https://raw.githubusercontent.com/xunit/xunit/master/license.txt
- http://raw.github.com/NLog/NLog/master/LICENSE.txt
- https://raw.github.com/HangfireIO/Hangfire/master/LICENSE.md
- https://raw.github.com/JamesNK/Newtonsoft.Json/master/LICENSE.md
- https://raw.github.com/timrwood/moment/master/LICENSE
- https://raw.github.com/StackExchange/StackExchange.Redis/master/LICENSE
- https://raw.github.com/jkowalski/NLog/master/LICENSE.txt
- …
> Increase tolerance for GitHub license urls

- CycloneDX.Tests/GithubServiceTests.cs
- CycloneDX/Services/GithubService.cs
Adds license support for the non-American spelling. And adds support for the main branch instead of only the master.
> Add flexibility to Regex and add main lookup

- CycloneDX/Services/ProjectFileService.cs
**Problem:**
`ProjectFileService` relies on `ProjectReference` msbuild item to allways have `Include` attribute. 
That however doesn't need to be present in some special cases (`Update` or `Remove` attributes are possible as well - see e.g.: https://github.com/dotnet/runtime/blob/main/eng/references.targets#L19).
**Solution:**
Skipping the items without include attribute.
In ideal case the Remove should be special case handled as well - but that's outside of scope of this change
> Fix null reference in project reference resolving

- CycloneDX.Tests/SolutionFileServiceTests.cs
- CycloneDX/Program.cs
- CycloneDX/Utils.cs
- README.md
Allow parsing of F# projects in addition to C# and VB.
Includes a test (which fails without the fix) of a solution file.
Appears to work fine locally on a couple of production systems.
Fixes #572
> allow parsing of F# projects

- CycloneDX/Program.cs
When excluded component it still needs to be in the mapping for subsequent usage
Bug introduced in 2.4.x causing null reference exceptions on run across every repo we have which upgraded.
Priority: Blocker ☹️
Fixes: #601
> Fix adding to packageToComponent

- CycloneDX/Models/NugetInputModel.cs
- CycloneDX/Services/NugetV3Service.cs
What happens currently: `NugetInputModel.Create` ignores the `baseUrl` argument it receives, representing the user-specified `--url` command-line argument, unless access credentials (user name / password for the alternate NuGet URL) are also specified.
What changes in this commit: `NugetInputModel.Create` stores the value of `baseUrl` regardless of whether credentials are specified or not. In turn, `NugetV3Service.SetupNugetRepository` is updated to use `baseUrl` when specified, otherwise fall back to the default value `https://api.nuget.org/v3/index.json`.
Fixes https://github.com/CycloneDX/cyclonedx-dotnet/issues/597
> Address https://github.com/CycloneDX/cyclonedx-dotnet/issues/597

- CycloneDX/Services/ProjectFileService.cs
Detect test projects based on the `Microsoft.NET.Test.Sdk` reference. Fixes #363.
> Detect test projects by test SDK reference

- CycloneDX.Tests/GithubServiceTests.cs
- CycloneDX.Tests/NugetV3ServiceTests.cs
- CycloneDX/Services/GithubService.cs
- CycloneDX/Services/NugetV3Service.cs
Have seen situations whereby the licence URL isn't github (often when it's a file) and using the repository (or project) url then locates the licence
Logic now locates licence based on this order
* Expression in the package (this is where Nuget has found the licence itself)
* Licence URL node
* Repository node with commit SHA
* Repository node without ref
* Project URL
These checks all assume that the URLs are github, the github service will only check valid URLs
Secondary updates to the GitHub service:
* Use the actual licence URL for the located licence (sometimes this differs from the input URL)
* Allow a licence lookup with a base repository URL - use the current default branch licence
> Additional Lookups For Licence

- CycloneDX.Tests/GithubServiceTests.cs
- CycloneDX.Tests/NugetV3ServiceTests.cs
- CycloneDX/CycloneDX.csproj
- CycloneDX/Services/GithubService.cs
* If getting licence and repository URL ends ".git" and you get a NOTFOUND (404) try again without ".git"
* Add support for the URL being a SSH URL (git@github.com/owner/repo.git)
* Add Cache of URL to licence so if same URL requested, return from the previous result rather than getting again from GitHub
> GitHub Performance & Edge case improvements

- CycloneDX/Services/NugetV3Service.cs
The Author and Publisher are distinct fields, and feels like this should be used for Author.
https://cyclonedx.org/docs/1.4/json/#components_items_author 
https://cyclonedx.org/docs/1.4/json/#components_items_publisher
/cc @fgreinacher
> fix: populate authors as Author, not Publisher

- CycloneDX.Tests/ProjectAssetsFileServiceTests.cs
- CycloneDX/Program.cs
- CycloneDX/Services/ProjectAssetsFileService.cs
Fixes #725 
I also adjusted the tests to reflect the possibility of having runtimes being set to avoid regression in the future.
> Fix framework resolution when resolving dependencies

- CycloneDX.Tests/GithubServiceTests.cs
- CycloneDX/Services/GithubService.cs
There are cases where the GitHub licence call returns a JSON that has a spdxId and a license name.
Example: https://api.github.com/repos/aspnet/AspNetWebStack/license
`  "license": {
"key": "other",
"name": "Other",
"spdx_id": "NOASSERTION",
"url": null,
"node_id": "MDc6TGljZW5zZTA="
}`
This is problematic for two reason:
- A cycloneDX licence tag must have either a name or an spdx_id, not both.
- NOASSERTION is not a valid value for the spdx_id enumeration.
Obviously, NOASSERTION is not a meaningful value, which makes an easy solution to just replace it with null. In the given example, the licence is more or less correctly identified by its name "other" as it cannot be matched to a licence.
For the future, it might be worth the consideration that the class GithubService should only …
> Replace licenseID NOASSERTION with null

- CycloneDX/Program.cs
Fixes #751: Automatically generate a BOM metadata timestamp if none is provided with the metadata.
This approach does not require any additional command line parameters.
> Generate BOM metadata timestamp

- CycloneDX.Tests/NugetV3ServiceTests.cs
- CycloneDX.Tests/ValidationTests.cs
- CycloneDX/Program.cs
- CycloneDX/Services/NugetV3Service.cs
This sets the license name to `Unknown - See URL` if the `--disable-github-licenses` parameter has been specified. Leaving the name unspecified causes the resulting JSON formatted BOM to not validate against the [1.4 JSON schema](https://github.com/CycloneDX/specification/blob/1.4/schema/bom-1.4.schema.json#L600-L610) because it requires that either `id` or `name` is specified.
Fixes #754.
> Fix json validation when using license url

- CycloneDX.Tests/CycloneDX.Tests.csproj
- CycloneDX.Tests/FunctionalTests/DevDependnciesWithPackageConfig.cs
- CycloneDX.Tests/FunctionalTests/ExcludeDevDepenceny.cs
- CycloneDX.Tests/FunctionalTests/ExcludeDevDependnciesWithPackageConfig.cs
- CycloneDX.Tests/FunctionalTests/FunctionalTestHelper.cs
- CycloneDX.Tests/FunctionalTests/TestcaseFiles/DevDependencies.json
- CycloneDX.Tests/FunctionalTests/TestcaseFiles/DevDependencies_WithPackageConfig_CsProj.xml
- CycloneDX.Tests/FunctionalTests/TestcaseFiles/DevDependencies_WithPackageConfig_PackageConfig.xml
- CycloneDX.Tests/ProgramTests.cs
- CycloneDX.Tests/ProjectAssetsFileServiceTests.cs
- CycloneDX.Tests/ProjectFileServiceTests.cs
- CycloneDX.Tests/ValidationTests.cs
- CycloneDX/Interfaces/IProjectAssetsFileService.cs
- CycloneDX/Interfaces/IProjectFileService.cs
- CycloneDX/Interfaces/ISolutionFileService.cs
- CycloneDX/Runner.cs
- CycloneDX/Services/PackagesFileService.cs
- CycloneDX/Services/ProjectAssetsFileService.cs
- CycloneDX/Services/ProjectFileService.cs
- CycloneDX/Services/SolutionFileService.cs
feat: DevDependencies also work for packages.config
fix: excluded DevDependencies won't appear in the dependencyTree any more #761
> fix: exluded DevDependencies won't appear in the dependencyTree anymore #761

- .github/workflows/issue-close-inactive.yml
- .github/workflows/issue-label-triage.yml
- many issues are outdated and should be closed (older than 1 year)
- new issues should be checked and appropriate labels assigned (contributor need permission to assign labels)
> automation for issues (close inactive, triage)

- .github/workflows/release.yml
This should have prevented #806 
Generally, it's a good idea to check if the container works before publishing it.
> Create bom.json in docker container as smoke test (#806)

- CycloneDX.Tests/CycloneDX.Tests.csproj
- CycloneDX.Tests/FunctionalTests/Issue826-ProjectFileDoesntExist/ReferencedProjectFileDoesntExists.cs
- CycloneDX.Tests/FunctionalTests/Issue826-ProjectFileDoesntExist/project1csproj.xml
- CycloneDX.Tests/FunctionalTests/Issue826-ProjectFileDoesntExist/solution1sln.text
- CycloneDX/Services/ProjectFileService.cs
The tool doesn't check condition in .csproj-file. Conditional project references will always be considered regular project references.
Thus, it can happen that a .csproj-file doesn't actually exist in the current environment. The solution is to check if the file exists and return some replacement values if it doesn't.
This is still not really supported, the resulting SBOM might be wrong, but at least it doesn't crash.
> Fix crash when a projectfile doesn't existent #826

- CycloneDX.Tests/CycloneDX.Tests.csproj
- CycloneDX.Tests/FunctionalTests/TestcaseFrameworkPackagesConfigRecursive/FrameworkPackagesConfigRecursive.cs
- CycloneDX.Tests/FunctionalTests/TestcaseFrameworkPackagesConfigRecursive/packages1.config
- CycloneDX.Tests/FunctionalTests/TestcaseFrameworkPackagesConfigRecursive/packages2.config
- CycloneDX.Tests/FunctionalTests/TestcaseFrameworkPackagesConfigRecursive/project1csproj.xml
- CycloneDX.Tests/FunctionalTests/TestcaseFrameworkPackagesConfigRecursive/project2csproj.xml
- CycloneDX/Services/ProjectFileService.cs
Added a testcase for `-rs` with `packages.config`.
Fixed a bug, that dependencies in that case were not linked in the dependency graph.
> Recursive package config dependency graph

- CycloneDX.Tests/ProjectFileServiceTests.cs
- CycloneDX/Services/ProjectFileService.cs
The AssemblyInfo file for VB has a different file path and syntax than C#, so assembly version information for VB projects was not getting picked up by the ProjectFileService.
> Add VB assembly version info

- CycloneDX.Tests/ProgramTests.cs
- CycloneDX/Runner.cs
https://github.com/CycloneDX/cyclonedx-dotnet/issues/882
> CycloneDX should fail when the provided file was not found

- CycloneDX.Tests/FunctionalTests/FunctionalTestHelper.cs
- CycloneDX.Tests/ValidationTests.cs
- CycloneDX/Services/NugetV3Service.cs
- Directory.Packages.props
Updated FunctionalTestHelper.cs and ValidationTests.cs to support BOM validation for Specification Version v1_6 in both JSON and XML formats. Upgraded CycloneDX.Core package version in Directory.Packages.props from 7.0.1 to 8.0.0. Also corrected a minor formatting issue in Directory.Packages.props.
> Update CycloneDX to 8.0.0 and BOM validation to v1_6

- CycloneDX.Tests/ProjectFileServiceTests.cs
- CycloneDX.Tests/SolutionFileServiceTests.cs
- CycloneDX/Program.cs
- CycloneDX/Runner.cs
- CycloneDX/Services/ProjectFileService.cs
- CycloneDX/Utils.cs
- README.md
* add support for X# project files with the .xsproj extension
* add support for extracting version from AssemblyInfo.prg file for X# project files
Signed-off-by: Volkmar Rigo <Volkmar.rigo@Infominds.eu>
> feat: Support X# Project files (#895)

- CycloneDX/CycloneDX.csproj
Enables installing and running `CycloneDX` on runtimes/SDKs newer than those that it targets when published. (For instance, allows v4.0.0 to run with only .NET SDK 9.0 installed, and no 8.0, 7.0 or 6.0 present.)
ref. https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#major-version-runtime-roll-forward
ref. https://github.com/dotnet/sdk/issues/26824
Examples of other tools which have this setting enabled:
- `dotnet-format` (MS): https://github.com/dotnet/format/blob/ad8125a6fc036fe1eb4e57aa604a79f2d98d5aa0/src/dotnet-format.csproj#L11  -- added in https://github.com/dotnet/format/commit/7a5df81d357992e66bf88b6dd664d70569bd7f21
- `dotnet-ef` (MS): https://github.com/dotnet/efcore/blob/486047c7422ec04530ca66c7c55256fa89b0ffc2/src/dotnet-ef/dotnet-ef.csproj#L24 -- added …
> Enable `RollForward` to run on the latest .NET SDKs

- CycloneDX/Services/ProjectFileService.cs
A fix for #896.  When processing recursively through projects to get references, apply the supported project test and skip any projects that do not satisfy the test.  It uses the existing utility method IsSupportedProjectType
> Unsupported project types are included in the..

- CycloneDX.Tests/NugetV3ServiceTests.cs
- CycloneDX/Services/NugetV3Service.cs
An attempt to normalise the contents of the VCS URL to handle SCP-like Git URLs.
The behaviour is to:
- Skip adding the external reference in the event the VCS URL cannot be normalised.
- Add the https URL scheme (because modifying it to this scheme worked when cloning from GitHub, unlike alternatives).
I successfully validated the produced SBOM and uploaded it to Dependency Track.
#890
> Add normalisation logic to VCS URL

- CycloneDX.Tests/SolutionFileServiceTests.cs
- CycloneDX/Program.cs
- CycloneDX/Runner.cs
- CycloneDX/Services/SolutionFileService.cs
This Pull Request aim to support the new solution format .slnx, that was released together with .NET 9.0.200.
It goes with the old approach and uses regex to read the projects path, before start reading the solution file it checks if it is a .sln or .slnx and then call the macthing private method.
> feat: Enable .slnx solutions to be analyzed

- CycloneDX/Services/NugetV3Service.cs
Resolve an issue where versions with uppercase characters (e.g., 1.0.0-Beta, 1.0.0.BETA.1) caused CycloneDX to throw errors. The
problem occurred because the NuGet cache converted version strings to lowercase for path names. This caused the .nuspec file to not be found.
> Fix Error with Uppercase Characters in Version Strings

- CycloneDX.Tests/CycloneDX.Tests.csproj
- CycloneDX.Tests/FunctionalTests/DependencyFiltering/DependencyFilteringTest.cs
- CycloneDX.Tests/FunctionalTests/DependencyFiltering/netstandard.assets.json
- CycloneDX.Tests/FunctionalTests/DependencyFiltering/shared_dependency.assets.json
- CycloneDX.Tests/FunctionalTests/FunctionalTestHelper.cs
- CycloneDX/ExcludeFilterHelper.cs
- CycloneDX/Models/RunOptions.cs
- CycloneDX/Program.cs
- CycloneDX/Runner.cs
- README.md
We use CycloneDX-Dotnet for creating an SBOM for a project which targets .NET 8. Some transient dependencies are fairly old like [Antlr3.Runtime](https://www.nuget.org/packages/Antlr3.Runtime), so .NETStandard 1.6.1 will be pulled into the resulting SBOM including many old libraries, which will not be used by our application. They do not exist in the binary build output, so these dependencies should be removed from the resulting SBOM.
We could not find any existing feature request for dependency filtering in CycloneDX-Dotnet or CycloneDX-CLI. There is only a command line option for filtering test projects and development dependencies, but no option to provide a custom filter. So we decided to implement a custom filter option by ourselves. Please consider this feature as an improvement for …
> Add exclude filter option
