CycloneDX/cyclonedx-dotnet

- .github/workflows/dotnetcore.yml
This pull request will make tests run automatically for pull requests.
It's a draft pull request as I have temporarily failed a test to validate it works as expected.
> Run tests automatically for pull requests

- CycloneDX/Models/GithubLicense.cs
- CycloneDX/Services/GithubService.cs
- CycloneDX/Services/NugetService.cs
Potential fix for #30.
I don't see a contribution policy so I tried to keep things as close as possible to other classes in the project.
Waiting for feedback on this :)
> Added license handling using Github API when possible.

- CycloneDX.Core/Models/Bom.cs
- CycloneDX.Core/Models/Component.cs
- CycloneDX.Core/Services/BomService.cs
- CycloneDX.Core/Services/Utf8TextWriter.cs
- CycloneDX/Program.cs
Adds a Bom model and refactors the BomService to use it
> Initial refactoring in preparation for JSON support

- CycloneDX.Core/CycloneDX.Core.csproj
- CycloneDX.Core/Models/Bom.cs
- CycloneDX.Core/Models/Component.cs
- CycloneDX.Core/Services/BomService.cs
- CycloneDX.Core/Services/NugetService.cs
- CycloneDX/Program.cs
- README.md
Initial work for #122 @stevespringett I've only manually tested the JSON output so far.
But thought it might be good to get this out in the wild with JSON output a "preview" feature. What do you think?
> Add initial preview support for JSON output

- CycloneDX.Core/Services/GithubService.cs
- CycloneDX/Program.cs
- README.md
> Add support for github bearer tokens (useful for github action usage)

- .github/workflows/dotnetcore.yml
Use custom SxS .NET version SDK installation action until an official solution is available for https://github.com/actions/setup-dotnet/issues/25
> Replace awful .NET SDK side by side hack with custom action

- CycloneDX.Core/Services/DotnetCommandService.cs
- CycloneDX.Core/Services/IDotnetCommandService.cs
- CycloneDX/Program.cs
> Add parameter to override the default dotnet command timeout

- CycloneDX.Core/Services/ProjectAssetsFileService.cs
- CycloneDX.IntegrationTests/IntegrationTests.cs
- CycloneDX.IntegrationTests/Resources/ProjectWithProjectReferences/ProjectReference/Class1.cs
- CycloneDX.IntegrationTests/Resources/ProjectWithProjectReferences/ProjectReference/ProjectReference.csproj
- CycloneDX.IntegrationTests/Resources/ProjectWithProjectReferences/ProjectWithProjectReferences.sln
- CycloneDX.IntegrationTests/Resources/ProjectWithProjectReferences/ProjectWithProjectReferences/ProjectWithProjectReferences.csproj
- CycloneDX.IntegrationTests/__snapshots__/Tests.CallingCycloneDX_WithProjectPath_GeneratesBom_ProjectWithProjectReferences_ProjectWithProjectReferences_csproj_Json.snap
- CycloneDX.IntegrationTests/__snapshots__/Tests.CallingCycloneDX_WithProjectPath_GeneratesBom_ProjectWithProjectReferences_ProjectWithProjectReferences_csproj_Xml.snap
- CycloneDX.IntegrationTests/__snapshots__/Tests.CallingCycloneDX_WithSolutionFilePath_GeneratesBom_ProjectWithProjectReferences_Json.snap
- CycloneDX.IntegrationTests/__snapshots__/Tests.CallingCycloneDX_WithSolutionFilePath_GeneratesBom_ProjectWithProjectReferences_Xml.snap
> Exclude local project references

- CycloneDX.IntegrationTests/IntegrationTests.cs
- CycloneDX.IntegrationTests/__snapshots__/Tests.CallingCycloneDX_ExcludesDevelopmentDependencies.snap
- CycloneDX/Program.cs
- README.md
> Exclude dev dependencies

- CycloneDX.Core/Services/GithubService.cs
- CycloneDX/ExitCode.cs
- CycloneDX/Program.cs
> Output some helpful information if GitHub license resolution fails

- .github/workflows/dotnetcore.yml
- .github/workflows/release.yml
- CycloneDX.Core.Tests/CycloneDX.Core.Tests.csproj
- CycloneDX.IntegrationTests/CycloneDX.IntegrationTests.csproj
- CycloneDX.Tests/CycloneDX.Tests.csproj
- CycloneDX/CycloneDX.csproj
- Dockerfile
- README.md
> Add support for .NET 5

- .github/workflows/release.yml
- .gitignore
- CycloneDX/CycloneDX.csproj
> Fix release versioning

- CycloneDX.Core.Tests/ProjectFileServiceTests.cs
- CycloneDX.Core/Services/IProjectAssetsFileService.cs
- CycloneDX.Core/Services/ProjectAssetsFileService.cs
- CycloneDX.Core/Services/ProjectFileService.cs
- CycloneDX.Core/Services/SolutionFileService.cs
- CycloneDX.IntegrationTests/IntegrationTests.cs
- CycloneDX.IntegrationTests/Resources/ProjectWithTestProject/CSharp/CSharp.csproj
- CycloneDX.IntegrationTests/Resources/ProjectWithTestProject/ProjectWithTestProject.sln
- CycloneDX.IntegrationTests/Resources/ProjectWithTestProject/TestProject/TestProject.csproj
- CycloneDX.IntegrationTests/Resources/TestProject/TestProject.sln
- CycloneDX.IntegrationTests/Resources/TestProject/TestProject/TestProject.csproj
- CycloneDX.IntegrationTests/__snapshots__/Tests.CallingCycloneDX_WithProjectPath_GeneratesBom_TestProject_TestProject_csproj_Json.snap
- CycloneDX.IntegrationTests/__snapshots__/Tests.CallingCycloneDX_WithProjectPath_GeneratesBom_TestProject_TestProject_csproj_Xml.snap
- CycloneDX.IntegrationTests/__snapshots__/Tests.CallingCycloneDX_WithSolutionFilePath_GeneratesBom_ProjectWithTestProject_Json.snap
- CycloneDX.IntegrationTests/__snapshots__/Tests.CallingCycloneDX_WithSolutionFilePath_GeneratesBom_ProjectWithTestProject_Xml.snap
- CycloneDX.IntegrationTests/__snapshots__/Tests.CallingCycloneDX_WithSolutionFilePath_GeneratesBom_TestProject_Json.snap
- CycloneDX.IntegrationTests/__snapshots__/Tests.CallingCycloneDX_WithSolutionFilePath_GeneratesBom_TestProject_Xml.snap
Related to issue #415 
Signed-off-by: Patrick Spaeth <patrick.spaeth@t-online.de>
> Packages from Testprojects will marked as scope="excluded"

- CycloneDX.Tests/ComponentServiceTests.cs
- CycloneDX.Tests/NugetServiceTests.cs
- CycloneDX.Tests/ProgramTests.cs
- CycloneDX/Models/NugetPackage.cs
- CycloneDX/Program.cs
- CycloneDX/Services/BomService.cs
- CycloneDX/Services/ComponentService.cs
- CycloneDX/Services/GithubService.cs
- CycloneDX/Services/NugetService.cs
- CycloneDX/Services/ProjectAssetsFileService.cs
> Produce v1.3 CycloneDX BOMs

- CycloneDX/Models/NugetPackage.cs
- CycloneDX/Services/NugetService.cs
> Fix component null scope issue for packages.config files

- .github/workflows/dotnetcore.yml
- .github/workflows/release.yml
- CycloneDX/Models/NugetPackage.cs
- CycloneDX/Program.cs
- CycloneDX/Services/NugetService.cs
- CycloneDX/Services/ProjectAssetsFileService.cs
> Initial implementation of dependency graph

- CycloneDX/Program.cs
> Add top level BOM metadata component for complete dependency graph

- CycloneDX.Tests/ProjectFileServiceTests.cs
- CycloneDX/Program.cs
- CycloneDX/Services/IProjectFileService.cs
- CycloneDX/Services/ProjectFileService.cs
- README.md
Fix #447 
Signed-off-by: Davide Icardi <davide.icardi@gmail.com>
> Allow to disable package restore

- .gitpod.yml
- CycloneDX.Tests/CycloneDX.Tests.csproj
- CycloneDX/CycloneDX.csproj
- Dockerfile
- README.md
> Add support for .NET 6

- CycloneDX/Models/NugetPackage.cs
- CycloneDX/Program.cs
- CycloneDX/Services/ProjectAssetsFileService.cs
Signed-off-by: Patrick Spaeth <patrick.spaeth@t-online.de>
> Fix #453: Dependency identification not only over name but also with version

- CycloneDX.Tests/ProgramTests.cs
- CycloneDX.Tests/ProjectFileServiceTests.cs
- CycloneDX/Interfaces/IDotnetUtilsService.cs
- CycloneDX/Interfaces/IProjectFileService.cs
- CycloneDX/Interfaces/ISolutionFileService.cs
- CycloneDX/Program.cs
- CycloneDX/Services/DotnetUtilsService.cs
- CycloneDX/Services/ProjectFileService.cs
- CycloneDX/Services/SolutionFileService.cs
Resolves #622 
I made an implementation for my user story. I tried it against my complex project and it creates the expected results.
> Add framework and runtime flags

- .gitpod.yml
- CycloneDX.Tests/CycloneDX.Tests.csproj
- CycloneDX.sln
- CycloneDX/CycloneDX.csproj
- CycloneDX/Services/ProjectFileService.cs
- Directory.Build.props
- Directory.Packages.props
- README.md
- Microsoft introduced CPM which simplifies nuget package handling  see also https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management#transitive-pinning
- update all dependecies
> use central package management and update dependencies

- CycloneDX.Tests/NugetV3ServiceTests.cs
- CycloneDX/Services/NugetV3Service.cs
Why: Nuget will normalize the version string according to 
https://learn.microsoft.com/en-us/nuget/concepts/package-versioning#normalized-version-numbers, 
when creating the local cache. Thus, a version "1.0.0.0" will be stored in folder "1.0.0" and the nupkg 
and nupkg.sha512 files will be named accordingly.
How: This change adds a Normalize method to strip off the Revision number under certain conditions, before locating the files in the cache.
Fixes #673, relates to #603
> Normalize version string when locating files in the local cache

- CycloneDX/Program.cs
- README.md
> add URL for "DevelopmentDependency support for PackageReference"

- Directory.Packages.props
> update Nuget and test dependencies

- .codacy.yml
- .gitignore
- .markdownlint.json
- CycloneDX.sln
- CycloneDX/CycloneDX.csproj
- CycloneDX/README.md
- Directory.Build.props
- fixes #643
- adds README.md for NuGet package
> fix PackageReleaseNotes URL

- CycloneDX/Services/ProjectFileService.cs
Intended to improve upon the IsTestProject method so that the --exclude-test-projects option works with csproj XMLs that have the msbuild namespace (or other namespaces assuming the XML structure is the same). See #669.
Sorry if I did this wrong, I tried to follow the contribution guidelines but this is the first time I've contributed to a public project and I'm a little confused.
> Updated IsTestProject to use available XML namespace
